local SpecialCaracters = {"@", "#", "$", "&", "*"}
local Numbers = {"0", "1", "2", "3", "4", "5", "6", "7", "8", "9"}
local LowerCaseLetters = {"a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"}
local UpperCaseLetters = {"A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"}
local D1 = math.random(1, 4)
local D2 = math.random(1, 4)
local D3 = math.random(1, 4)
local D4 = math.random(1, 4)
local D5 = math.random(1, 4)
local D6 = math.random(1, 4)
local D7 = math.random(1, 4)
local D8 = math.random(1, 4)
local D9 = math.random(1, 4)
local D10 = math.random(1, 4)
local D11 = math.random(1, 4)
local D12 = math.random(1, 4)
local D13 = math.random(1, 4)
local D14 = math.random(1, 4)
local D15 = math.random(1, 4)

if D1 == 1 then 
	D1 = SpecialCaracters[math.random(1, 6)]
elseif D1 == 2 then
	D1 = Numbers[math.random(1, 9)]
elseif D1 == 3 then 
	D1 = LowerCaseLetters[math.random(1, 26)]
elseif D1 == 4 then
	D1 = UpperCaseLetters[math.random(1, 26)]
end

if D2 == 1 then 
	D2 = SpecialCaracters[math.random(1, 6)]
elseif D2 == 2 then
	D2 = Numbers[math.random(1, 9)]
elseif D2 == 3 then 
	D2 = LowerCaseLetters[math.random(1, 26)]
elseif D2 == 4 then
	D2 = UpperCaseLetters[math.random(1, 26)]
end

if D3 == 1 then 
	D3 = SpecialCaracters[math.random(1, 6)]
elseif D3 == 2 then
	D3 = Numbers[math.random(1, 9)]
elseif D3 == 3 then 
	D3 = LowerCaseLetters[math.random(1, 26)]
elseif D3 == 4 then
	D3 = UpperCaseLetters[math.random(1, 26)]
end

if D4 == 1 then 
	D4 = SpecialCaracters[math.random(1, 6)]
elseif D4 == 2 then
	D4 = Numbers[math.random(1, 9)]
elseif D4 == 3 then 
	D4 = LowerCaseLetters[math.random(1, 26)]
elseif D4 == 4 then
	D4 = UpperCaseLetters[math.random(1, 26)]
end

if D5 == 1 then 
	D5 = SpecialCaracters[math.random(1, 6)]
elseif D5 == 2 then
	D5 = Numbers[math.random(1, 9)]
elseif D5 == 3 then 
	D5 = LowerCaseLetters[math.random(1, 26)]
elseif D5 == 4 then

if D6 == 1 then 
	D6 = SpecialCaracters[math.random(1, 6)]
elseif D6 == 2 then
	D6 = Numbers[math.random(1, 9)]
elseif D6 == 3 then 
	D6 = LowerCaseLetters[math.random(1, 26)]
elseif D6 == 4 then
	D6 = UpperCaseLetters[math.random(1, 26)]
end

if D7 == 1 then 
	D7 = SpecialCaracters[math.random(1, 6)]
elseif D7 == 2 then
	D7 = Numbers[math.random(1, 9)]
elseif D7 == 3 then 
	D7 = LowerCaseLetters[math.random(1, 26)]
elseif D7 == 4 then
	D7 = UpperCaseLetters[math.random(1, 26)]
end

if D8 == 1 then 
	D8 = SpecialCaracters[math.random(1, 6)]
elseif D8 == 2 then
	D8 = Numbers[math.random(1, 9)]
elseif D8 == 3 then 
	D8 = LowerCaseLetters[math.random(1, 26)]
elseif D8 == 4 then
	D8 = UpperCaseLetters[math.random(1, 26)]
end

if D9 == 1 then 
	D9 = SpecialCaracters[math.random(1, 6)]
elseif D9 == 2 then
	D9 = Numbers[math.random(1, 9)]
elseif D9 == 3 then 
	D9 = LowerCaseLetters[math.random(1, 26)]
elseif D9 == 4 then
	D9 = UpperCaseLetters[math.random(1, 26)]
end

if D10 == 1 then 
	D10 = SpecialCaracters[math.random(1, 6)]
elseif D10 == 2 then
	D10 = Numbers[math.random(1, 9)]
elseif D10 == 3 then 
	D10 = LowerCaseLetters[math.random(1, 26)]
elseif D10 == 4 then
	D10 = UpperCaseLetters[math.random(1, 26)]
end

if D11 == 1 then 
	D11 = SpecialCaracters[math.random(1, 6)]
elseif D11 == 2 then
	D11 = Numbers[math.random(1, 9)]
elseif D11 == 3 then 
	D11 = LowerCaseLetters[math.random(1, 26)]
elseif D11 == 4 then
	D11 = UpperCaseLetters[math.random(1, 26)]
end

if D12 == 1 then 
	D12 = SpecialCaracters[math.random(1, 6)]
elseif D12 == 2 then
	D12 = Numbers[math.random(1, 9)]
elseif D12 == 3 then 
	D12 = LowerCaseLetters[math.random(1, 26)]
elseif D12 == 4 then
	D12 = UpperCaseLetters[math.random(1, 26)]
end
if D13 == 1 then
	D13 = SpecialCaracters[math.random(1, 6)]
elseif D13 == 2 then
	D13 = Numbers[math.random(1, 9)]
elseif D13 == 3 then 
	D13 = LowerCaseLetters[math.random(1, 26)]
elseif D13 == 4 then
	D13 = UpperCaseLetters[math.random(1, 26)]
end

if D14 == 1 then 
	D14 = SpecialCaracters[math.random(1, 6)]
elseif D14 == 2 then
	D14 = Numbers[math.random(1, 9)]
elseif D14 == 3 then 
	D14 = LowerCaseLetters[math.random(1, 26)]
elseif D14 == 4 then
	D14 = UpperCaseLetters[math.random(1, 26)]
end

if D15 == 1 then 
	D15 = SpecialCaracters[math.random(1, 6)]
elseif D15 == 2 then
	D15 = Numbers[math.random(1, 9)]
elseif D15 == 3 then 
	D15 = LowerCaseLetters[math.random(1, 26)]
elseif D15 == 4 then
	D15 = UpperCaseLetters[math.random(1, 26)]
end

print(D1.. D2.. D3.. D4.. D5.. D6.. D7.. D8.. D9.. D10.. D11.. D12.. D13.. D14.. D15)
