local SpecialCaracters = {"@", "#", "$", "&", "*"}
local Numbers = {"0", "1", "2", "3", "4", "5", "6", "7", "8", "9"}
local LowerCaseLetters = {"a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"}
local UpperCaseLetters = {"A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"}
local D1 = math.random(1, 4)
local D2 = math.random(1, 4)
local D3 = math.random(1, 4)
local D4 = math.random(1, 4)
local D5 = math.random(1, 4)
local D6 = math.random(1, 4)
local D7 = math.random(1, 4)
local D8 = math.random(1, 4)
local D9 = math.random(1, 4)
local D10 = math.random(1, 4)
local D11 = math.random(1, 4)
local D12 = math.random(1, 4)
local D13 = math.random(1, 4)
local D14 = math.random(1, 4)
local D15 = math.random(1, 4)

if D1 == 1 then 
	D1 = SpecialCaracters[math.random(1, 6)
elseif D1 == 2 then
	D1 = Numbers[math.random(1, 9)
elseif D1 == 3 then 
	D1 = LowerCaseLetters[math.random(1, 26)
elseif D1 == 4 then
	D1 = UpperCaseLetters[math.random(1, 26)
end

if D2 == 1 then 
	D2 = SpecialCaracters[math.random(1, 6)
elseif D2 == 2 then
	D2 = Numbers[math.random(1, 9)
elseif D2 == 3 then 
	D2 = LowerCaseLetters[math.random(1, 26)
elseif D2 == 4 then
	D2 = UpperCaseLetters[math.random(1, 26)
end

if D3 == 1 then 
	D3 = SpecialCaracters[math.random(1, 6)
elseif D3 == 2 then
	D3 = Numbers[math.random(1, 9)
elseif D3 == 3 then 
	D3 = LowerCaseLetters[math.random(1, 26)
elseif D3 == 4 then
	D3 = UpperCaseLetters[math.random(1, 26)
end

if D6 == 1 then 
	D6 = SpecialCaracters[math.random(1, 6)
elseif D6 == 2 then
	D6 = Numbers[math.random(1, 9)
elseif D6 == 3 then 
	D6 = LowerCaseLetters[math.random(1, 26)
elseif D6 == 4 then
	D6 = UpperCaseLetters[math.random(1, 26)
end

if D6 == 1 then 
	D6 = SpecialCaracters[math.random(1, 6)
elseif D6 == 2 then
	D6 = Numbers[math.random(1, 9)
elseif D6 == 3 then 
	D6 = LowerCaseLetters[math.random(1, 26)
elseif D6 == 4 then
	D6 = UpperCaseLetters[math.random(1, 26)
end

if D7 == 1 then 
	D7 = SpecialCaracters[math.random(1, 6)
elseif D7 == 2 then
	D7 = Numbers[math.random(1, 9)
elseif D7 == 3 then 
	D7 = LowerCaseLetters[math.random(1, 26)
elseif D7 == 4 then
	D7 = UpperCaseLetters[math.random(1, 26)
end

